Models/ErrorViewModel.cs
using System;

namespace SalvandoHuellas.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SalvandoHuellas.Models;

namespace SalvandoHuellas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PetsController.cs
using Microsoft.AspNetCore.Mvc;

namespace SalvandoHuellas.Controllers
{
    public class PetsController: Controller
    {
        public IActionResult Index(){
            return View();
        }
        public IActionResult Contactanos(){
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Pets/Contactanos.cshtml
<form>
    <h1 class="text-center">Tus comentarios nos ayudaran a mejorar nuestros servicios</h1>
    <div class="form-group">
        <label for="exampleFormControlInput1">Correo Electronico:</label>
        <input type="email" class="form-control col-md-4" id="exampleFormControlInput1" placeholder="name@example.com">
    </div>
    
    <div class="form-group">
        <label for="exampleFormControlInput1">Titulo:</label>
        <input type="text" class="form-control col-md-4" id="exampleFormControlInput1" placeholder="Que te parece nuestro trabajo">
    </div>
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Comentario</label>
        <textarea class="form-control text-tarea" id="exampleFormControlTextarea1" rows="3" ></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Enviar comentario</button>
</form>

Views/Pets/Index.cshtml
<main>
    <section class="bg-primary font-weight-bolder text-white p-5">
        <span class=" title-info">¡Salvando Angelitos!</span>
        <div class="content-info text-center">
            Buscamos ser una organizacion sin fines de lucro que lucha en pro de los
            derechos de los perros, que se encuentran en un entorno de maltrato, abandono,
            enfermedad.Intentamos reintegrarlos a una sociedad que tenga el deseo de poder
            adoptarlos u apadrinarlos para mejorar su calidad de vida.
        </div>

    </section>


    <section>
        <img class="img p-5" src="~/images/unidos.jpg" alt="">
    </section>
    <h1 class=" text-center font-weight-bold">¿Quienes Somos?</h1>
    <hr>
    <section class=" d-flex justify-content-center .bg-light p-4">
        <div class="content-conocenos d-flex ">
            <div class="quienes-somos bg-info">
                <div class="content-description">
                    <h5 class="text-center font-weight-bold">Mision</h5>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum consectetur ipsum quidem quod
                        ducimus rem magni debitis iste. Animi architecto quis ducimus similique maxime earum, quod
                        repellat provident iste alias perspiciatis ipsum ipsam aperiam debitis explicabo dicta natus.
                        Esse repudiandae aliquid blanditiis corrupti in maxime. Dolor alias fuga et soluta.</p>

                </div>
            </div>
             <div class="quienes-somos">
                <div class="content-description">
                    <h5 class="text-center font-weight-bold">Vision</h5>
                    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum consectetur ipsum quidem quod
                        ducimus rem magni debitis iste. Animi architecto quis ducimus similique maxime earum, quod
                        repellat provident iste alias perspiciatis ipsum ipsam aperiam debitis explicabo dicta natus.
                        Esse repudiandae aliquid blanditiis corrupti in maxime. Dolor alias fuga et soluta.</p>

                </div>
            </div>
        </div>
    </section>
    <h1 class=" text-center font-weight-bold pt-3">¿Como Contribuir?</h1>

    <hr>
    <section class="d-flex d-flex justify-content-around cards bg-dark pt-5 pb-5">
        <div class="card" style="width: 18rem;">
            <div class="p-3">
                <img class="card-img-top car-image" src="~/images/adoptame.jpg" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">Puedes contribuir con la fundacion al adoptar un perrito,
                        brindandole el cariño y el amor que nesesita.
                    </p>
                </div>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="p-3">
                <img class="card-img-top car-image" src="~/images/apadriname.jpg" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">Puedes apadrinar un perrito si no deseas adoptar, hasta el momento
                        que alguien mas desee adoptarlo.</p>
                </div>
            </div>
        </div>
        <div class="card" style="width: 18rem;">
            <div class="p-3">
                <img class="card-img-top car-image" src="~/images/aporte.jpg" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">No necesariamente con dinero, puede ser alimentos, jabones
                        u cualquier cosa de nesesidad basica
                    </p>
                </div>
            </div>
        </div>


    </section>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SalvandoHuellas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container ">
                <a class="navbar-brand  text-primary font-weight-bolder"  asp-controller="Pets"
                    asp-action="Index">SalvandoHuellas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pets" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pets"
                                asp-action="Contactanos">Contacto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class=>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="  text-muted mt-5 bg-warning">
        <div class="pie-info">
            <span class="text-center mb-5">Nuestras redes sociales:</span>
            <div class="redes d-flex justify-content-around">
                <a class="icon p-3"  href="https://www.instagram.com/">
                    <span  class="fa fa-instagram  fa-5x"></span>
                </a>
                <a class="icon p-3"  href="https://www.facebook.com/">
                    <span  class="fa fa-facebook  fa-5x"></span>
                </a>
                <a class="icon p-3"  href="https://www.whatsapp.com/">
                    <span  class="fa fa-whatsapp  fa-5x"></span>
                </a>
                <a class="icon p-3"  href="https://www.whatsapp.com/">
                    <span  class="fa fa-youtube  fa-5x"></span>
                </a>
            </div>
            <div class="bg-dark text-white">
            &copy; 2021 - SalvandoHuellas - Donado por SoftSystem 
        </div>
        </div>
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>